## galicaster-capture-agents-datapath-common/tasks
---

- name: "Remove Datapath Drivers"
  apt: >
          pkg=datapath-vision-drivers
          state=absent
          force=yes
  register: datapath_driver_removed
  tags:
          - datapath
          - datapath_drivers

- name: "Install Datapath Drivers"
  apt: >
          pkg=datapath-vision-drivers
          state=latest
          force=yes
  when: datapath_driver_removed
  register: datapath_driver_installed
  changed_when: datapath_driver_installed.stdout is defined and datapath_driver_installed.stdout | search("Flash requires upgrading, please wait")
  tags:
          - datapath
          - datapath_drivers

- name: "Datapath Profiles"
  template: >
          src=profiles/{{ item }}
          dest=/etc/galicaster/profiles/{{ item }}
          group={{ ca_username }}
          owner={{ ca_username }}
  with_items:
          - datapath-split.ini
          - datapath-usb.ini
          - dual-datapath-split.ini
          - dual-datapath-usb.ini
          - datapath-no-usb.ini
          - dual-datapath-no-usb.ini
          - no-video-usb.ini
  notify: restart galicaster
  tags:
          - galicaster
          - galicaster_config
          - galicaster_profiles
          - datapath
